### PR TITLE
[WIP/Test] Style/game layout: transitions for card states

### PR DESCRIPTION
**Pull request by evaplaysviolin**
### **I added temporary code into the game play file just so people can see what the transitions look like, but in practice we should be adding/removing the classes according to state. So this isn't really a pull request lol.**

I added click events to the first two cards. Let me know if the colors are okay or whatever you might have comments on:
image
image
image
image

@serpient I think the shared Sass file is kind of a mess now, not sure what's best practice for organizing (like if you reuse colors, how do you note that?).

### CODE REVIEW

**Comment by evaplaysviolin** [comment]
By the way, I realize that this branch isn't good with master - but if the transitions are given the okay I'll go back in and delete the code causing conflicts before the "real" PR (or, accept the changes from master, it just means we won't be able to see the transitions until we write code for it).

**Review by serpient — APPROVED** [review]
looks good! def a good start for transitions for now.

**Comment by serpient** [comment]
@evaplaysviolin  what do you mean, if you reuse colors in the scss file?

**Comment by evaplaysviolin** [comment]
I mean, for instance, if I have "$grey" - I want to label it with what I used it for, say "header".

// Header
$grey = #whatever;

But if I want to also use that grey variable for, say, paragraph text, is there some standard way to note that? Or is the standard not to note this kind of thing at all? Right now, the way I have it, it looks like:

// Header
$grey
...
...
...
...
// Paragraph
// $grey

Is it a problem to declare it again? What do you normally do?

**Review by kellyburg — APPROVED** [review]

**Pull request merged**
