### PR TITLE
Card branch

### PR DESCRIPTION
**Pull request by AnutaK**

### CODE REVIEW

**Comment by AnutaK** [comment]
@evaplaysviolin, @kellyburg , @enjoyli-h , @serpient , I added a .gitignore file. Please take a look and  merge when you have a chance.

**Review by serpient — CHANGES_REQUESTED** [review]
node_modules is already set to ignore near the top of the file :D

**Review by evaplaysviolin — COMMENTED** [review]
Looks fine to me except for the change already requested (repetition of node_modules).

**Review by serpient — APPROVED** [review]

**Comment by AnutaK** [comment]
@serpient , I made the change. Please review when you can! Thank you!

**Pull request merged**
